spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**

        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/api/storage/**

        - id: storage-s3-route
          uri: lb://storage-service
          predicates:
            - Path=/api/s3/**

        - id: vm-service
          uri: lb://vm-service
          predicates:
            - Path=/api/vm/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
